Creating contract
 -> (Pair (Pair None "tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf") (Pair "tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ" (Pair 30 1)))
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testContractStorage.0.0.tz 1
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testContractStorage.0.0.tz.json 7
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testContractTypes.0.0.txt 5
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testContractCode.0.0.tz 279
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testContractCode.0.0.tz.json 293
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_called_with_stale_asset_data_interpreted/testPrettyPrint.0.0.py 43
Executing getXtzUsdRate_callback(('XTZ-USD', (sp.timestamp(29), 2310000)))...
 -> --- Expected failure in transaction --- WrongCondition in line 101: sp.as_nat(sp.now - sp.fst(sp.snd(params))) < self.data.maxDataDelaySec [17]