Creating contract
 -> (Pair (Pair None "tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf") (Pair "tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ" (Pair 1800 1)))
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractStorage.0.0.tz 1
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractStorage.0.0.tz.json 7
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractTypes.0.0.txt 5
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractCode.0.0.tz 279
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractCode.0.0.tz.json 293
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testPrettyPrint.0.0.py 43
Creating contract
 -> (Pair 0 0)
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractStorage.1.1.tz 1
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractStorage.1.1.tz.json 1
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractTypes.1.1.txt 5
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractCode.1.1.tz 34
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testContractCode.1.1.tz.json 40
 => ./.smartpy_out/getXtzUsdRate_-_fails_when_called_from_bad_state_interpreted/testPrettyPrint.1.1.py 17
Executing getXtzUsdRate(sp.contract(sp.TNat, sp.contract_address(Contract1), entry_point='natCallback').open_some())...
 -> --- Expected failure in transaction --- WrongCondition in line 61: self.data.state == 0 [12]