Creating contract
 -> (Pair (Pair None "tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf") (Pair "tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ" (Pair 1800 1)))
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testContractStorage.0.0.tz 1
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testContractStorage.0.0.tz.json 7
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testContractTypes.0.0.txt 5
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testContractCode.0.0.tz 279
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testContractCode.0.0.tz.json 293
 => ./.smartpy_out/getXtzUsdRate_callback_-_fails_when_not_called_from_harbinger_interpreted/testPrettyPrint.0.0.py 43
Executing getXtzUsdRate_callback(('XTZ-USD', (sp.timestamp(1632869468), 2310000)))...
 -> --- Expected failure in transaction --- WrongCondition in line 95: sp.sender == self.data.harbingerContractAddress [3]